image: wmyl/deploy

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
  - vendor/
  - node_modules/

before_script:
  - npm install
  - npm -g install bower
  - bower install --allow-root
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$DEPLOY_KEY")

stages:  
  - deploy

deploy_to_staging:
  stage: deploy
  only:
    - develop
  script:
    - npm run build
    - rsync -rv * deploy@stuff.wmyl.se:/var/www/ml-2017.stuff.wmyl.se/web/ --exclude '.git' --exclude '.gitlab-ci.yml' --exclude '.gitignore' --exclude 'node_modules' --exclude 'src'
